INSERT INTO bej.categoria (id, descripcion,activo,ultimamodificacion)
	VALUES
--PERSONAS
(1, 'Propietario','S',now()),
(10, 'Cliente Persona Fisica','S',now()),
(15, 'Cliente Persona Juridica','S',now()),
(20, 'Proveedor','S',now()),
--TRANSACCION
(40,'Compra de Moto al Contado','S',now()),
(45,'Compra de Moto a Credito','S',now()),
(50,'Venta de Moto al Contado','S',now()),
(55,'Venta de Moto a Credito','S',now()),
--CREDITOS
(60,'Sistema Frances','S',now()),
(62,'Personalizado','S',now()),
(65,'Sistema Aleman','S',now()),
(69,'Especial','S',now()),
--MOTOS
(30, 'Moto de dama','S',now()),
(35, 'Moto trail','S',now()),
(36, 'Moto carga','S',now()),
--FACTURAS
(70, 'Factura de Compra Contado','S',now()),
(75, 'Factura de Compra Credito','S',now()),
(77, 'Factura de Venta Contado','S',now()),
(79, 'Factura de Venta Credito','S',now());

INSERT INTO bej.ubicacion (activo, descripcion, `ultimaModificacion`) 
	VALUES ('S', 'Salon Central', now()),('S', 'Salon 104', now()),('S', 'Deposito Central', now()),('S', 'Deposito 104', now());


insert into bej.persona(documento,tratamiento,categoria,nombre,direccion1,telefono_fijo,telefono_movil,email,Fecha_Ingreso,habilitado,estado_civil,fisica,activo,ultimaModificacion) values 
('1275758','Sra.',1,'Jacinta Diosmede Benitez Britez','14 de Mayo c/ Gral Caballero',232126,null,'jbenitez@bej.com.py',now(),'S','C','S','S',now()),
('80021319-6','S.R.L.',20,'ALEX S.A.','Tacuaras',null,null,null,now(),'S','S','N','S',now()),
('1012077','Sr.',10,'Adela Rojas de Palacios','Tacuaras',null,null,null,now(),'S','S','S','S',now()),
('1335795','Sr.',10,'Hugo Gustavo Guillen Martinez','Mburica',null,null,null,now(),'S','S','S','S',now()),
('1366971','Sr.',10,'Dionicio Francisco Ortiz Rojas','San Juan Bautista-Ñeembucu',null,null,null,now(),'S','S','S','S',now());

INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'HPDLX65R','S','MSTEGRFDG','HERO PUCH','DLX65 MAGNESIO','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'HPSTD65A','S','MSTEGRFDG','HERO PUCH','STD65','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'HPSTD65R','S','MSTEGRFDG','HERO PUCH','STD65','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'HPSTD65V','S','MSTEGRFDG','HERO PUCH','STD65','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'Husqvrna240','S','MSTEGRFDG','Husqvarna','240','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC100DLXA','S','MSTEGRFDG','KENTON','C100 DLX','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC100DLXVN','S','MSTEGRFDG','KENTON','C100 DLX','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC100SEA','S','MSTEGRFDG','KENTON','C100 SE','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC100SER','S','MSTEGRFDG','KENTON','C100 SE','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC100SEVM','S','MSTEGRFDG','KENTON','C100 SE','VERDE METAL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC100SEVN','S','MSTEGRFDG','KENTON','C100 SE','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110A','S','MSTEGRFDG','KENTON','C110','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110R','S','MSTEGRFDG','KENTON','C110','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110TPA','S','MSTEGRFDG','KENTON','C110 TOP','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110TPR','S','MSTEGRFDG','KENTON','C110 TOP','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110TPVM','S','MSTEGRFDG','KENTON','C 110 TOP','VERDE METAL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110TPVN','S','MSTEGRFDG','KENTON','C110 TOP','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110VM','S','MSTEGRFDG','KENTON','C110','VERDE METAL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC110VN','S','MSTEGRFDG','KENTON','C110','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC70A','S','MSTEGRFDG','KENTON','C70','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC70DLXA','S','MSTEGRFDG','KENTON','C70DLX','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC70DLXVN','S','MSTEGRFDG','KENTON','C70DLX','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC70R','S','MSTEGRFDG','KENTON','C70','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC70VM','S','MSTEGRFDG','KENTON','C70','VERDE METAL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEC70VN','S','MSTEGRFDG','KENTON','C70','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECARGA150A','S','MSTEGRFDG','KENTON','TRICICLO  CARGA 150','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECARGA200A','S','MSTEGRFDG','KENTON','TRICICLO CARGA200','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI110A','S','MSTEGRFDG','KENTON','CITY 110','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI110AMG','S','MSTEGRFDG','KENTON','CITY 110','AZUL/GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI110R','S','MSTEGRFDG','KENTON','CITY 110','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI110RMG','S','MSTEGRFDG','KENTON','CITY 110','ROJO / GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI110V','S','MSTEGRFDG','KENTON','CITY','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI125A','S','MSTEGRFDG','KENTON','CITY 125','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI125AM','S','MSTEGRFDG','KENTON','CITY','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI125R','S','MSTEGRFDG','KENTON','CITY 125','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECI125RM','S','MSTEGRFDG','KENTON','CITY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KECUS150V','S','MSTEGRFDG','KENTON','CUSTON 150','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEDAK150AB','S','MSTEGRFDG','KENTON','DAKAR 150','AZUL BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEDAK150NG','S','MSTEGRFDG','KENTON','150cc','Negro/Gris',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEDAK150RB','S','MSTEGRFDG','KENTON','DAKAR150CC','ROJO BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEDAK200AB','S','MSTEGRFDG','KENTON','DAKAR','AZUL BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEDAK200AMG','S','MSTEGRFDG','KENTON','DAKAR 200CC','AMARILLO GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEDAK200NG','S','MSTEGRFDG','KENTON','DAKAR 200cc','NEGRO/GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEDAK200RB','S','MSTEGRFDG','KENTON','DAKAR 200cc','ROJO/BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KEGL150R','S','MSTEGRFDG','KENTON','GL150','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KENX100CAA','S','MSTEGRFDG','KENTON','CARGA NX 100','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'KESCO125AG','S','MSTEGRFDG','KENTON','SCOOTER 125','AZUL/GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEEN125YESA','S','MSTEGRFDG','LEOPARD','EN125 YES','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEEN125YESN','S','MSTEGRFDG','LEOPARD','EN 125','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEEN125YESR','S','MSTEGRFDG','LEOPARD','EN 125','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEEN150YESN','S','MSTEGRFDG','LEOPARD','EN150YES','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEEN150YESR','S','MSTEGRFDG','LEOPARD','EN150YES','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEEN200YESN','S','MSTEGRFDG','LEOPARD','EN200YES','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEEN200YESR','S','MSTEGRFDG','MOTOSTAR','SK 110-A2','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEGSX150A','S','MSTEGRFDG','LEOPARD','GSX150','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEGSX150N','S','MSTEGRFDG','LEOPARD','GSX150','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEGSX150R','S','MSTEGRFDG','LEOPARD','GSX150','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEHB125WEBB','S','MSTEGRFDG','LEOPARD','HB125 WEB','Bordo',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEHB125WEBN','S','MSTEGRFDG','LEOPARD','HB125 WEB','Negro',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110-2NR','S','MSTEGRFDG','LEOPARD','MC110-2A','NEGRO/ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110-3A','S','MSTEGRFDG','LEOPARD','MC110-3','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110-3AB','S','MSTEGRFDG','LEOPARD','MC 110-3A','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110-3AN','S','MSTEGRFDG','LEOPARD','MC110-3A','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110-3AP','S','MSTEGRFDG','LEOPARD','MC 110-3A','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110A-A','S','MSTEGRFDG','LEOPARD','MC 110A','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110A-B','S','MSTEGRFDG','LEOPARD','MC 110A','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110B','S','MSTEGRFDG','LEOPARD','MC110','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC110P','S','MSTEGRFDG','LEOPARD','MC110','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC125B','S','MSTEGRFDG','LEOPARD','MC125','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMC125N','S','MSTEGRFDG','LEOPARD','MC125','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD1252A','S','MSTEGRFDG','LEOPARD','MD125-2','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD1252R','S','MSTEGRFDG','LEOPARD','MD125-2','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD125A','S','MSTEGRFDG','LEOPARD','MD125','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD125B','S','MSTEGRFDG','LEOPARD','MD125','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD125N','S','MSTEGRFDG','LEOPARD','MD 125','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD125R','S','MSTEGRFDG','LEOPARD','MD 125','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150-2B','S','MSTEGRFDG','LEOPARD','MD 150-2','Bordo',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150-2N','S','MSTEGRFDG','LEOPARD','MD 150-2','Negro',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150A','S','MSTEGRFDG','LEOPARD','MD 150','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150B','S','MSTEGRFDG','LEOPARD','MD 150','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150L','S','MSTEGRFDG','LEOPARD','MD 150','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150N','S','MSTEGRFDG','LEOPARD','MD150','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150R','S','MSTEGRFDG','LEOPARD','MD-150','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150-SA','S','MSTEGRFDG','LEOPARD','MD150 SPORT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150-SB','S','MSTEGRFDG','LEOPARD','MD150-SPORT','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMD150-SN','S','MSTEGRFDG','LEOPARD','MD150-SPORT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMF 110A','S','MSTEGRFDG','LEOPARD','MF 110','Azul',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMF 110B','S','MSTEGRFDG','LEOPARD','MF 110','Bordo',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMF 110N','S','MSTEGRFDG','LEOPARD','MF 110','Negro',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMF 110R','S','MSTEGRFDG','LEOPARD','MF 110','Rojo',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEML150CO2N','S','MSTEGRFDG','LEOPARD','ML 150 -2','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEML150COPN','S','MSTEGRFDG','LEOPARD','ML150 CHOPPER-1','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEML150COPV','S','MSTEGRFDG','LEOPARD','ML 150 COPPER','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEML200NJAA','S','MSTEGRFDG','LEOPARD','ML200 NJA','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEML200SNJN','S','MSTEGRFDG','LEOPARD','ML200S','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEML200SNJR','S','MSTEGRFDG','LEOPARD','ML 200S','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT 150LA','S','MSTEGRFDG','LEOPARD','MT150L','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT 150LN','S','MSTEGRFDG','LEOPARD','MT150L','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT 150LR','S','MSTEGRFDG','LEOPARD','MT150L','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT125GYN','S','MSTEGRFDG','LEOPARD','MT125GY','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT125GYR','S','MSTEGRFDG','LEOPARD','MT 125 GY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT150GYR','S','MSTEGRFDG','LEOPARD','MT150GY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT200GYA','S','MSTEGRFDG','LEOPARD','MT200GY','Azul',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT200GYN','S','MSTEGRFDG','LEOPARD','MT200GY','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'LEMT200GYR','S','MSTEGRFDG','LEOPARD','MT200GY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGADV150AA','S','MSTEGRFDG','MAGNUM','ADVENTURA 150','AZUL AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGADV150AN','S','MSTEGRFDG','MAGNUM','150 ADVENTURE','AMARILLO-NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGADV150R','S','MSTEGRFDG','MAGNUM','ADVENTURE','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGCR150VM','S','MSTEGRFDG','MAGNUM','CRUISER 150','VERDE METAL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC100A','S','MSTEGRFDG','MAGNUM','MC100','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC100R','S','MSTEGRFDG','MAGNUM','MC100','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC100VM','S','MSTEGRFDG','MAGNUM','MC100','VERDE METAL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC100VN','S','MSTEGRFDG','MAGNUM','MC100','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC110A','S','MSTEGRFDG','MAGNUM','MC110','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC110R','S','MSTEGRFDG','MAGNUM','MC110','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC110VM','S','MSTEGRFDG','MAGNUM','MC110','VERDE METAL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGMC110VN','S','MSTEGRFDG','MAGNUM','MC110','VINO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGML110A','S','MSTEGRFDG','MAGNUM','ML 110','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGML110N','S','MSTEGRFDG','MAGNUM','ML 110','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGML110R','S','MSTEGRFDG','MAGNUM','ML 110','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGML150A','S','MSTEGRFDG','MAGNUM','ML150','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGML150N','S','MSTEGRFDG','MAGNUM','ML 150','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MGML150R','S','MSTEGRFDG','MAGNUM','ML 150','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMC1002RA','S','MSTEGRFDG','MARUTI','MC100-2','ROJO/AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMC1102FA','S','MSTEGRFDG','MARUTI','MC110-2','FUCSIA / AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMC1102RA','S','MSTEGRFDG','MARUTI','MC110-2','ROJO/AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMC1102RN','S','MSTEGRFDG','MARUTI','MC110-2','ROJO/NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMC110B','S','MSTEGRFDG','MARUTI','MC110','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMC110P','S','MSTEGRFDG','MARUTI','MC110','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMD100A','S','MSTEGRFDG','MARUTI','MD 100','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMD100B','S','MSTEGRFDG','MARUTI','MD100','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMD100N','S','MSTEGRFDG','MARUTI','MD100','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMD100R','S','MSTEGRFDG','MARUTI','MD100','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMD125B','S','MSTEGRFDG','MARUTI','MD125','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMD125N','S','MSTEGRFDG','MARUTI','MD125','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMT125LR','S','MSTEGRFDG','MARUTI','MT125','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MIMT125LV','S','MSTEGRFDG','MARUTI','MT125L','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100B','S','MSTEGRFDG','MONTANA','MF100','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100C','S','MSTEGRFDG','MONTANA','MF100','CELESTE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100L','S','MSTEGRFDG','MONTANA','MF100','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100MGA','S','MSTEGRFDG','MONTANA','MF100-MAG','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100MGB','S','MSTEGRFDG','MONTANA','MF100-MAG','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100MGC','S','MSTEGRFDG','MONTANA','MF100 MAG','CELESTE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100MGL','S','MSTEGRFDG','MONTANA','MF100 MAG','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100MGN','S','MSTEGRFDG','MONTANA','MF100 MAG','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100MGR','S','MSTEGRFDG','MONTANA','MF100','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100N','S','MSTEGRFDG','MONTANA','MF100','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MOMF100R','S','MSTEGRFDG','MONTANA','MF100','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSAX100A','S','MSTEGRFDG','MOTOSTAR','AX100-2T','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG125A','S','MSTEGRFDG','MOTOSTAR','CG125','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG125B','S','MSTEGRFDG','MOTOSTAR','CG125','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG125N','S','MSTEGRFDG','MOTOSTAR','CG125','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG125R','S','MSTEGRFDG','MOTOSTAR','CG125','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG150-A','S','MSTEGRFDG','MOTOSTAR','CG150','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG150-B','S','MSTEGRFDG','MOTOSTAR','CG150','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG150-N','S','MSTEGRFDG','MOTOSTAR','CG150','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSCG150-R','S','MSTEGRFDG','MOTOSTAR','CG150','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A1A','S','MSTEGRFDG','MOTOSTAR','SK100-A1','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A1G','S','MSTEGRFDG','MOTOSTAR','SK100-A1','GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A1N','S','MSTEGRFDG','MOTOSTAR','SK100-A1','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A1R','S','MSTEGRFDG','MOTOSTAR','SK100-A1','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A1V','S','MSTEGRFDG','MOTOSTAR','SK100-A1','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A2A','S','MSTEGRFDG','MOTOSTAR','SK100','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A2G','S','MSTEGRFDG','MOTOSTAR','SK100 -A2','GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A2N','S','MSTEGRFDG','MOTOSTAR','SK100-A2','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A2R','S','MSTEGRFDG','MOTOSTAR','SK100 - A2','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100A2V','S','MSTEGRFDG','MOTOSTAR','SK100-A2','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100-DYN','S','MSTEGRFDG','MOTOSTAR','SK100-DY','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100-DYP','S','MSTEGRFDG','MOTOSTAR','SK100-DY','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100-DYR','S','MSTEGRFDG','MOTOSTAR','SK100-DY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK100-DYV','S','MSTEGRFDG','MOTOSTAR','SK100-DY','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110-3A','S','MSTEGRFDG','MOTOSTAR','SK110-3','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110-3R','S','MSTEGRFDG','MOTOSTAR','SK110-3','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110-3V','S','MSTEGRFDG','MOTOSTAR','SK110-3','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A1A','S','MSTEGRFDG','MOTOSTAR','SK110-A1','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A1B','S','MSTEGRFDG','MOTOSTAR','SK110 A1','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A1L','S','MSTEGRFDG','MOTOSTAR','SK 110-A1','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A1N','S','MSTEGRFDG','MOTOSTAR','SK110-A1','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A1P','S','MSTEGRFDG','MOTOSTAR','SK110-A1','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A1R','S','MSTEGRFDG','MOTOSTAR','SK110-A1','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A1V','S','MSTEGRFDG','MOTOSTAR','SK110-A1','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2A','S','MSTEGRFDG','MOTOSTAR','SK110-A2','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2B','S','MSTEGRFDG','MOTOSTAR','SK110 A2','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2G','S','MSTEGRFDG','MOTOSTAR','SK110-A2','GRIS',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2L','S','MSTEGRFDG','MOTOSTAR','SK 110 A2','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2N','S','MSTEGRFDG','MOTOSTAR','SK110-A2','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2P','S','MSTEGRFDG','MOTOSTAR','SK110-A2','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2R','S','MSTEGRFDG','MOTOSTAR','SK110-A2','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110A2V','S','MSTEGRFDG','MOTOSTAR','SK110-A2','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110-A7B','S','MSTEGRFDG','MOTOSTAR','SK110-A7','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110-A7N','S','MSTEGRFDG','MOTOSTAR','SK110-A7','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110DAXA','S','MSTEGRFDG','MOTOSTAR','SK110-DAX','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110DAXAM','S','MSTEGRFDG','MOTOSTAR','SK 110 DAX','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110DAXAZ','S','MSTEGRFDG','MOTOSTAR','SK 110 DAX','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110DAXB','S','MSTEGRFDG','MOTOSTAR','SK110-DAX','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110DAXL','S','MSTEGRFDG','MOTOSTAR','SK DAX 110','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110DAXN','S','MSTEGRFDG','MOTOSTAR','SK110-DAX','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110JUNAM','S','MSTEGRFDG','MOTOSTAR','SK 110 JUNIOR','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110JUNAZ','S','MSTEGRFDG','MOTOSTAR','SK 110 JUNIOR','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110JUNB','S','MSTEGRFDG','MOTOSTAR','SK 110 JUNIOR','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110JUNL','S','MSTEGRFDG','MOTOSTAR','SK 110 JUNIOR','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110JUNN','S','MSTEGRFDG','MOTOSTAR','SK 110 JUNIOR','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110JUNP','S','MSTEGRFDG','MOTOSTAR','SK 110 JUNIOR','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110VIPB','S','MSTEGRFDG','MOTOSTAR','SK 110 -A7','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110WILDAZ','S','MSTEGRFDG','MOTOSTAR','WILD STAR A2','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110WILDB','S','MSTEGRFDG','MOTOSTAR','WILD STAR A2','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110WILDL','S','MSTEGRFDG','MOTOSTAR','WILD STAR A2','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110WILDN','S','MSTEGRFDG','MOTOSTAR','WILD STAR A2','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110WILDP','S','MSTEGRFDG','MOTOSTAR','WILD STAR A2','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK110WILDV','S','MSTEGRFDG','MOTOSTAR','WILD STAR A2','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-3A','S','MSTEGRFDG','MOTOSTAR','SK125-3','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-3R','S','MSTEGRFDG','MOTOSTAR','SK125-3','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-3V','S','MSTEGRFDG','MOTOSTAR','SK125-3','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-5A','S','MSTEGRFDG','MOTOSTAR','SK125-5','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-5B','S','MSTEGRFDG','MOTOSTAR','SK125-5','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-5N','S','MSTEGRFDG','MOTOSTAR','SK125-5','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-5R','S','MSTEGRFDG','MOTOSTAR','SK125-5','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK1257A','S','MSTEGRFDG','MOTOSTAR','SK125-7','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK1257R','S','MSTEGRFDG','MOTOSTAR','SK125-7','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-A7B','S','MSTEGRFDG','MOTOSTAR','SK125-A7','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125CGA','S','MSTEGRFDG','MOTOSTAR','SK 125-5','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125CGB','S','MSTEGRFDG','MOTOSTAR','SK 125-5','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125CGN','S','MSTEGRFDG','MOTOSTAR','SK 125 -5','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125CGR','S','MSTEGRFDG','MOTOSTAR','SK 125 - 5','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXA','S','MSTEGRFDG','MOTOSTAR','SK125-DAX','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXAM','S','MSTEGRFDG','MOTOSTAR','DAX PLUS 125','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXAZ','S','MSTEGRFDG','MOTOSTAR','DAX PLUS 125','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXB','S','MSTEGRFDG','MOTOSTAR','DAX 125','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXL','S','MSTEGRFDG','MOTOSTAR','DAX PLUS 125','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXN','S','MSTEGRFDG','MOTOSTAR','SK125DAX+','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXP','S','MSTEGRFDG','MOTOSTAR','SK125-DAX','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXR','S','MSTEGRFDG','MOTOSTAR','SK125-DAX','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125DAXVL','S','MSTEGRFDG','MOTOSTAR','SK 125 DAX PLUS','VERDE LIMON',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125GYAM','S','MSTEGRFDG','MOTOSTAR','ST125GY-3A','AMARILLO/AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125GYR','S','MSTEGRFDG','MOTOSTAR','SK125GY-3A','ROJO - NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-JA','S','MSTEGRFDG','MOTOSTAR','SK125-J','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-JN','S','MSTEGRFDG','MOTOSTAR','SK125-J','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125-JR','S','MSTEGRFDG','MOTOSTAR','SK125-J','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125JUNAM','S','MSTEGRFDG','MOTOSTAR','125 JUNIOR','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125JUNAZ','S','MSTEGRFDG','MOTOSTAR','125 JUNIOR','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125JUNB','S','MSTEGRFDG','MOTOSTAR','125 JUNIOR','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125JUNL','S','MSTEGRFDG','MOTOSTAR','125 JUNIOR','LILA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125JUNN','S','MSTEGRFDG','MOTOSTAR','125 JUNIOR','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125JUNP','S','MSTEGRFDG','MOTOSTAR','125 JUNIOR','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125PCGA','S','MSTEGRFDG','MOTOSTAR','CG125 PREMIUM','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125PCGB','S','MSTEGRFDG','MOTOSTAR','CG125 PREMIUM','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125PCGN','S','MSTEGRFDG','MOTOSTAR','CG125 PREMIUM','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125PCGR','S','MSTEGRFDG','MOTOSTAR','CG125 PREMIUM','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125XLA','S','MSTEGRFDG','MOTOSTAR','SK125-XL','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125XLB','S','MSTEGRFDG','MOTOSTAR','SK125-XL','BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK125XLR','S','MSTEGRFDG','MOTOSTAR','SK125-XL','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150 NTA','S','MSTEGRFDG','MOTOSTAR','SK150-NT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150 NTN','S','MSTEGRFDG','MOTOSTAR','SK150-NT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150 NTR','S','MSTEGRFDG','MOTOSTAR','SK150-NT','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-4A','S','MSTEGRFDG','MOTOSTAR','SK150-4','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-4GM','S','MSTEGRFDG','MOTOSTAR','HALCON 150 -4','GRIS MATE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-4N','S','MSTEGRFDG','MOTOSTAR','SK150-4','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-4NB','S','MSTEGRFDG','MOTOSTAR','150-4 HALCON','NEGRO BRILLANTE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-4NM','S','MSTEGRFDG','MOTOSTAR','150-4HALCON','NEGRO MATE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-4R','S','MSTEGRFDG','MOTOSTAR','SK150 - 4','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-7A','S','MSTEGRFDG','MOTOSTAR','SK150-7','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-7N','S','MSTEGRFDG','MOTOSTAR','SK150-7','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-7R','S','MSTEGRFDG','MOTOSTAR','SK150-7','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150A','S','MSTEGRFDG','MOTOSTAR','SK150-CG','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150ANTA','S','MSTEGRFDG','MOTOSTAR','NT 150 ALINEACION','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150B','S','MSTEGRFDG','MOTOSTAR','SK150-CG','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150CGA','S','MSTEGRFDG','MOTOSTAR','SK 150 CG','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150CGB','S','MSTEGRFDG','MOTOSTAR','SK150 CG','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150CGN','S','MSTEGRFDG','MOTOSTAR','SK 150 CG','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150CGR','S','MSTEGRFDG','MOTOSTAR','SK 150- CG','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150COPD','S','MSTEGRFDG','MOTOSTAR','SK150-2 CHOPPER','DORADO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150COPN','S','MSTEGRFDG','MOTOSTAR','SK150-2 CHOPPER','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DEPA','S','MSTEGRFDG','MOTOSTAR','SK150-DEP','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DEPAZ','S','MSTEGRFDG','MOTOSTAR','SK 150 DEP','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DEPB','S','MSTEGRFDG','MOTOSTAR','DEP 150','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DEPN','S','MSTEGRFDG','MOTOSTAR','SK150-DEP','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DEPR','S','MSTEGRFDG','MOTOSTAR','SK150-DEP','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DESA','S','MSTEGRFDG','MOTOSTAR','SK 150 DESSERT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DESN','S','MSTEGRFDG','MOTOSTAR','SK 150 DESERT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150DESR','S','MSTEGRFDG','MOTOSTAR','SK 150 DESERT','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150GYAM','S','MSTEGRFDG','MOTOSTAR','SK150-GY','AMARILLO-AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150GYRN','S','MSTEGRFDG','MOTOSTAR','SK150-GY','ROJO-NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150GYVB','S','MSTEGRFDG','MOTOSTAR','SK150-GY','VERDE-BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150HALA','S','MSTEGRFDG','MOTOSTAR','SK 150-4-HALCON','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150HALB','S','MSTEGRFDG','MOTOSTAR','SK150-4','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150HALGM','S','MSTEGRFDG','MOTOSTAR','SK 150-4-HALCON','GRIS MATE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150HALN','S','MSTEGRFDG','MOTOSTAR','SK 150-4-HALCON','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150HALNB','S','MSTEGRFDG','MOTOSTAR','SK 150-4-HALCON','NEGRO BRILLANTE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150HALNM','S','MSTEGRFDG','MOTOSTAR','SK 150-4-HALCON','NEGRO MATE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150HALR','S','MSTEGRFDG','MOTOSTAR','SK 150-4-HALCON','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150JA','S','MSTEGRFDG','MOTOSTAR','SK 150 - J','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-JA','S','MSTEGRFDG','MOTOSTAR','SK150-J','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150JN','S','MSTEGRFDG','MOTOSTAR','SK 150 - J','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-JN','S','MSTEGRFDG','MOTOSTAR','SK150-J','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150JR','S','MSTEGRFDG','MOTOSTAR','SK 150 - J','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150-JR','S','MSTEGRFDG','MOTOSTAR','SK150-J','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150N','S','MSTEGRFDG','MOTOSTAR','SK150-CG','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150NTA','S','MSTEGRFDG','MOTOSTAR','SK 150 NT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150NTB','S','MSTEGRFDG','MOTOSTAR','SK 150 NT','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150NTN','S','MSTEGRFDG','MOTOSTAR','SK 150 NT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150NTR','S','MSTEGRFDG','MOTOSTAR','SK 150 NT','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150PCGA','S','MSTEGRFDG','MOTOSTAR','CG150 PREMIUM','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150PCGB','S','MSTEGRFDG','MOTOSTAR','CG150 PREMIUM','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150PCGN','S','MSTEGRFDG','MOTOSTAR','CG150 PREMIUM','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150PCGR','S','MSTEGRFDG','MOTOSTAR','CG150 PREMIUM','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK150R','S','MSTEGRFDG','MOTOSTAR','SK150-CG','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200-2CH','S','MSTEGRFDG','MOTOSTAR','MSSK200-2CHOPPER','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200-7 R','S','MSTEGRFDG','MOTOSTAR','SK200-7','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200-7N','S','MSTEGRFDG','MOTOSTAR','SK200-7','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200-7P','S','MSTEGRFDG','MOTOSTAR','SK200-7','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200BRA','S','MSTEGRFDG','MOTOSTAR','SK 200BR DESERT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200CARGAA','S','MSTEGRFDG','MOTOSTAR','SKCARGA 200','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200CARGAAM','S','MSTEGRFDG','MOTOSTAR','SK200CARGA','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200CARGAB','S','MSTEGRFDG','MOTOSTAR','SK200CARGA','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200CARGAR','S','MSTEGRFDG','MOTOSTAR','SK200CARGA','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200CHPN','S','MSTEGRFDG','MOTOSTAR','200-2CHOPPER','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200CHPR','S','MSTEGRFDG','MOTOSTAR','200-2CHOPPER','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200DESA','S','MSTEGRFDG','MOTOSTAR','SK BR200 DESERT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200DESAM','S','MSTEGRFDG','MOTOSTAR','SK BR200 DESERT','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200DESAZ','S','MSTEGRFDG','MOTOSTAR','SK 200 DESERT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200DESN','S','MSTEGRFDG','MOTOSTAR','SK BR200 DESERT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200DESNP','S','MSTEGRFDG','MOTOSTAR','SK 200 DESERT','NEGRO/PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200DESR','S','MSTEGRFDG','MOTOSTAR','SK BR200 DESERT','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200FN','S','MSTEGRFDG','MOTOSTAR','SK200-FUEGO','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200FP','S','MSTEGRFDG','MOTOSTAR','SK200-FUEGO','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200FR','S','MSTEGRFDG','MOTOSTAR','SK200-FUEGO','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200GYA','S','MSTEGRFDG','MOTOSTAR','SK200-GY','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200GYAB','S','MSTEGRFDG','MOTOSTAR','SK200-GY','AZUL-BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200GYAM','S','MSTEGRFDG','MOTOSTAR','SK200-GY','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200GYR','S','MSTEGRFDG','MOTOSTAR','SK200-GY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200GYVB','S','MSTEGRFDG','MOTOSTAR','SK200-GY','VERDE-BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200NDESAZ','S','MSTEGRFDG','MOTOSTAR','NEW DESERT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200NDESN','S','MSTEGRFDG','MOTOSTAR','NEW DESERT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200NDESNP','S','MSTEGRFDG','MOTOSTAR','NEW DESERT','NEGRO PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200NDESR','S','MSTEGRFDG','MOTOSTAR','NEW DESERT 200','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200TUIA','S','MSTEGRFDG','MOTOSTAR','SK 200 SUPER TUISE','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200TUIB','S','MSTEGRFDG','MOTOSTAR','SK 200 SUPER TUISE','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200TUINP','S','MSTEGRFDG','MOTOSTAR','SK 200 SUPER TUISE','NEGRO/PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200XFA','S','MSTEGRFDG','MOTOSTAR','XF200GY-BA','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200XFN','S','MSTEGRFDG','MOTOSTAR','XF300GY-BA','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK200XFR','S','MSTEGRFDG','MOTOSTAR','XF200GY-BA','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK250MONSN','S','MSTEGRFDG','MOTOSTAR','SK 250 MONSTER','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSK250MONSR','S','MSTEGRFDG','MOTOSTAR','SK 250 MONSTER','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKA150NTA','S','MSTEGRFDG','MOTOSTAR','SK150-NT-A','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKA150NTN','S','MSTEGRFDG','MOTOSTAR','SK150-NT-A','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKA150NTR','S','MSTEGRFDG','MOTOSTAR','SK150-NT-A','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKBR200AM','S','MSTEGRFDG','MOTOSTAR','SKBR200DESERT','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKBR200N','S','MSTEGRFDG','MOTOSTAR','SKBR200DESERT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKBR200R','S','MSTEGRFDG','MOTOSTAR','SKBR200DESERT','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG125CA','S','MSTEGRFDG','MOTOSTAR','CG125C','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG125CB','S','MSTEGRFDG','MOTOSTAR','CG125C','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG125CN','S','MSTEGRFDG','MOTOSTAR','CG125C','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG125CR','S','MSTEGRFDG','MOTOSTAR','CG 125C','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG150A','S','MSTEGRFDG','MOTOSTAR','CG 150','Azul',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG150B','S','MSTEGRFDG','MOTOSTAR','SK 150- CG','BORDO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG150N','S','MSTEGRFDG','MOTOSTAR','CG150','Negro',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSSKCG150R','S','MSTEGRFDG','MOTOSTAR','CG150','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST1009A','S','MSTEGRFDG','MOTOSTAR','ST100-9','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST1009MGA','S','MSTEGRFDG','MOTOSTAR','ST100-9 MAG','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST1009MGR','S','MSTEGRFDG','MOTOSTAR','ST100-9 MAG','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST1009R','S','MSTEGRFDG','MOTOSTAR','ST100-9','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST1009V','S','MSTEGRFDG','MOTOSTAR','ST100-9','VERDE',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST100-A2R','S','MSTEGRFDG','MOTOSTAR','ST100-A2','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST100AMGP','S','MSTEGRFDG','MOTOSTAR','ST100-A-MAG','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125GYA','S','MSTEGRFDG','MOTOSTAR','ST125GY-3A','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125GYB','S','MSTEGRFDG','MOTOSTAR','ST125-GY','BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125GYR','S','MSTEGRFDG','MOTOSTAR','ST125-GY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125JA','S','MSTEGRFDG','MOTOSTAR','ST125-J','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125JN','S','MSTEGRFDG','MOTOSTAR','ST125-J','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125JR','S','MSTEGRFDG','MOTOSTAR','ST125-J','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125XLB','S','MSTEGRFDG','MOTOSTAR','ST125-XL','BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSST125XLR','S','MSTEGRFDG','MOTOSTAR','ST125-XL','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXF200ENDUR','S','MSTEGRFDG','MOTOSTAR','XF 200 SUPER ENDURO','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXF200MOTAAZ','S','MSTEGRFDG','MOTOSTAR','XF 200 MOTARD','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXF200MOTAR','S','MSTEGRFDG','MOTOSTAR','XF 200 MOTARD','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXF200RAENDUN','S','MSTEGRFDG','MOTOSTAR','XF 200 SUPER ENDURO','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110-5A','S','MSTEGRFDG','MOTOSTAR','XY110-5DAX','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110-5AM','S','MSTEGRFDG','MOTOSTAR','XY110-5DAX','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110-5N','S','MSTEGRFDG','MOTOSTAR','XY 110-5DAX','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110-5R','S','MSTEGRFDG','MOTOSTAR','XY110-5DAX','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110-5RO','S','MSTEGRFDG','MOTOSTAR','XY 110-5IV','ROSADO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110DAXA','S','MSTEGRFDG','MOTOSTAR','XY110-5DAX','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110DAXAM','S','MSTEGRFDG','MOTOSTAR','XY 110 -5 DAX','AMARILLO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110DAXN','S','MSTEGRFDG','MOTOSTAR','XY110-5DAX','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110DAXR','S','MSTEGRFDG','MOTOSTAR','XY110-5DAX','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY110IVP','S','MSTEGRFDG','SHINERAY','XY110IV','PLATA',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY125-10R','S','MSTEGRFDG','SHINERAY','XY125-10','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY125DAXA','S','MSTEGRFDG','MOTOSTAR','XY125-5DAX','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY125DAXN','S','MSTEGRFDG','MOTOSTAR','XY125-5 DAX','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY125DAXR','S','MSTEGRFDG','MOTOSTAR','XY125-5DAX','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY125GYVR','S','MSTEGRFDG','SHINERAY','XY125GYV','ROJO BLANCO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY150GYA','S','MSTEGRFDG','MOTOSTAR','XY150-GY','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY150GYIA','S','MSTEGRFDG','SHINERAY','XY150-GYI','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY150GYN','S','MSTEGRFDG','MOTOSTAR','XY150-GY','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY150GYR','S','MSTEGRFDG','MOTOSTAR','XY150-GY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY150NTA','S','MSTEGRFDG','MOTOSTAR','XY150NT','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY150NTN','S','MSTEGRFDG','MOTOSTAR','XY150NT','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY150NTR','S','MSTEGRFDG','MOTOSTAR','XY150NT','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY200FIN','S','MSTEGRFDG','MOTOSTAR','XY200-FIERA','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY200FIR','S','MSTEGRFDG','MOTOSTAR','XY200-FIERA','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY200GYA','S','MSTEGRFDG','MOTOSTAR','XY200-GY','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY200GYN','S','MSTEGRFDG','MOTOSTAR','XY200-GY','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY200GYR','S','MSTEGRFDG','MOTOSTAR','XY200-GY','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY250AMAZOAZ','S','MSTEGRFDG','MOTOSTAR','250 AMAZONA','AZUL',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY250AMAZON','S','MSTEGRFDG','MOTOSTAR','250 AMAZONA','NEGRO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY250AMAZOR','S','MSTEGRFDG','MOTOSTAR','250 AMAZONA','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY250CHPND','S','MSTEGRFDG','MOTOSTAR','XY 250 CHOPPER','NEGRO/DORADO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY250CHPR','S','MSTEGRFDG','MOTOSTAR','XY 250 CHOPPER','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'MSXY70Q-2R','S','MSTEGRFDG','SHINERAY','XY70Q-2','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'PLPL125R','S','MSTEGRFDG','PRISSA','PL125','ROJO',2,30);
INSERT INTO bej.moto(ultimaModificacion,codigo,activo,codigo_fabrica,marca,modelo,color,fabricante,categoria) values(NOW(),'STSK125DAXA','S','MSTEGRFDG','MOTOSTAR','SK 125 DAX','AMARILLO',2,30);